### ISSUE TITLE
[CONCEPT] Project Roadmap (short version) #EPIC

### ISSUE THREAD

**Issue by 1000miles** [1000miles/mind-the-board#1]
# TODO

**@Javathis**

- [ ] 1. Generate boilerplate with `passport` authentication
- [ ] 2. Setup `User` model with different roles
- [ ] 3. Create fake data (max 3) and seed them into the database
- [ ] 4. Create routes, controller and views for `User` model
- [ ] 5. Make authentication work (Signup, Login, session) with passport
- [ ] 6. Create CRUD methods for data from and to the database

**@1000miles**
- [ ] 7. Create templates for pages
  - [ ] 7.1 Index page
  - [ ] 7.1 Page after signup
  - [ ] 7.2 Page after login
- [ ] 8. Show data from the database on the pages

## Additional (if time)

- [ ] 9. Setup nodemailer to send
  - [ ] 9.1 Welcome email 
  - [ ] 9.2 Good-bye email

## Deployment

- [ ] Setup Heroku 
   - [ ] production
