### ISSUE TITLE
[API] Google Spreadsheet API

### ISSUE THREAD

**Issue by 1000miles** [1000miles/mind-the-board#10]
#TODO

- [ ] Register app on Google
- [ ] Create credentials
- [ ] Define a callback URL
- [ ] Retrieve data from a spreadsheet in the app
- [ ] Show imported data on `/google-api` page
