### ISSUE TITLE
[CONCEPT] WIP: Create a project roadmap #EPIC

### ISSUE THREAD

**Issue by 1000miles** [1000miles/mind-the-board#3]
A roadmap is an overview list of different phases of development. It contains estimated time, milestones, sprints, tasks and subtasks.

# Roadmap

## Milestone 1: Backend => 1 -1,5 Days (estimated)

1.1 **Sprint 1: Setup** (Thuy)

- [ ]  1.1.1 Initialize the project
    - [ ] 1.1.1.1 Setup Github repo
    - [ ] 1.1.1.2 Enable automated Project Board on Github
    - [ ]  1.1.1.2 Setup Herokuapp
    - [ ]  1.1.2 Create a mongoDB database and connect to the DB
    - [ ]  1.1.3 Install npm packages: Express, Mongoose, Midddleware 

- [ ] 1.2 **Sprint 2: Models** (Till)
   - [ ] 1.2.1 Admin (Phase 1/Prototype) - [Till]
      - [ ] 1.2.1.1 Create Admin model - [Till]
   - [ ] 1.2.2 User (Phase 2)
      - [ ] 1.2.2.1 Create User model
   - [ ] 1.2.3 Create <placeholder> Model (Phase 3)
   - [ ] 1.2.2 API
      - [ ] 1.2.2.1 Google Spreadsheet API
        - [ ] 1.2.2.1.1 Research Google Spreadsheet
     - [ ] 1.2.2.2 Register Google App
     - [ ] 1.2.2.3 Retrieve Data from Google Spreadsheet
     - [ ] 1.2.2.4 

- [ ] 1.3 **Sprint 3: Routes**
   - [ ] 1.3.1 Admin (Phase 1/Prototype) - [Till]
      - [ ] 1.3.1.1 Create Admin model - [Till]
      - [ ] 1.3.1.2 Create routes for Admin model - [Till]
   - [ ] 1.3.2 User (Phase 2)
      - [ ] 1.3.2.1 Create routes for User model
   - [ ] 1.3.3 Create routes for <placeholder> model (Phase 3)

  - [ ] 1.4 **Sprint 4: Views**
     - [ ] 1.4.1 Admin (Phase 1/Prototype) - [Till]
        - [ ] 1.4.1.1 Create Admin views - [Till]
     - [ ] 1.4.2 User (Phase 2)
         - [ ] 1.4.2.1 Create User views
    - [ ] 1.4.3 Create <placeholder> views (Phase 3)

## Milestone 2: Retrieve & Store Data => 1-1,5 Days

- [ ] 2.1 **Sprint 1: Connect to SOURCE API **(e.g. Google Spreadsheet)
   - [ ] 2.1.1 Retrieve Data from SOURCE API

- [ ] 2.2  **Sprint 1: Connect to DESTINATION API (Trello)**
    - [ ] 2.2.1 Show Data from SOURCE API in Trello

## Milestone 3: Frontend => 1 Day

TBA
