### ISSUE TITLE
[DEPLOY] Setup Heroku App for project

### ISSUE THREAD

**Issue by 1000miles** [1000miles/mind-the-board#5]
## PRODUCTION

**#TODO:**

- [ ] Register app on heroku
- [ ] Invite @Javathis to Heroku
- [ ] Setup production environment
- [ ] Add ssh keys for deployment
- [ ] Install packages
  - [ ] mlab

## STAGING

TBA

Helpful Links:
- https://devcenter.heroku.com/articles/multiple-environments
- https://devcenter.heroku.com/articles/heroku-cli
- https://devcenter.heroku.com/articles/git
